name: song_requester
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  riverpod_annotation: ^4.0.2
  shadcn_ui: ^0.46.2

dev_dependencies:
  build_runner: ^2.11.1
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  go_router_builder: ^4.2.0
  json_serializable: ^6.13.0
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3
  very_good_analysis: ^10.2.0

dependency_overrides:
  analyzer: ^10.0.0
  build: ^4.0.4
  source_gen: ^4.2.0

flutter:
  generate: true
  uses-material-design: true
